### ISSUE TITLE
AppData doesn't contain releases information

### ISSUE THREAD

**Issue by danirabbit** [ckruse/ColorMate#2]
Hey there! While reviewing your submission to AppCenter I noticed that your appdata doesn't contain any releases information. In order to be published in AppCenter, there should be a `<releases>` tag as described here: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases

**Comment by ckruse** [comment]
Thank you for the review. I added a releases entry; do I have to release a new version?

**Comment by ckruse** [comment]
I did release a new version
