### ISSUE TITLE
Flatpak manifest points to a local directory

### ISSUE THREAD

**Issue by danirabbit** [ckruse/ColorMate#3]
Hey there, while reviewing your app submission for AppCenter I noticed that your app fails to build on the server because it points to a local directory on your own computer as the path of its source files.

To resolve this, you could change the sources type from `git` to `dir` and the `url` to `path` which points to `.`

You can reference this documentation for an equivalent manifest in YML https://docs.elementary.io/develop/writing-apps/our-first-app/packaging

I would also recommend setting up CI so that you can be sure your Flatpak manifest is valid and building successfully. See these docs for more on that: https://docs.elementary.io/develop/writing-apps/our-first-app/continuous-integration

**Comment by ckruse** [comment]
Huh, that's an oversight. Sorry. Fixed that.

Will implement CI as soon as I have some spare time…
