### ISSUE TITLE
Values not updating when using the color picker dialog

### ISSUE THREAD

**Issue by johnillo** [ckruse/ColorMate#4]
I think the values should also be updated when the color selection dialog is used.

![colormate-ng-from-picker](https://user-images.githubusercontent.com/46668114/132959441-57405d1f-87be-4a11-ae4c-a85ea256c9ee.gif)

**Comment by ckruse** [comment]
Yup, it should, you are right. Will have a look at it tomorrow morning.

**Comment by ckruse** [comment]
This will be available after review: https://github.com/elementary/appcenter-reviews/pull/126
