### ISSUE TITLE
New Icon

### ISSUE THREAD

**Issue by adithyankv** [ckruse/ColorMate#5]
Hey there,
I feel like the present app Icon is a bit too busy and doesn't really read well at smaller sizes. It also doesn't adhere very well to elementary HIG guidelines. Would you be open to a new Icon? I can try and design one that follows elementary HIG.

**Comment by ckruse** [comment]
Hey,

I am aware that it is not the best icon possible, it was just the best I could come up with. So since I am not very good at this kind of things: yes, I am open for a new icon :-)

Best regards,  
 CK

**Comment by adithyankv** [comment]
Perhaps we could keep the color wheel idea and simplify it a bit so that it reads better? 
made a couple of variants off that idea.
![wheel-demo](https://user-images.githubusercontent.com/29067795/133946687-ee42f4f8-e211-4e57-b6f7-b745def04890.png)
Do you like any of these? Or should I try something different?

**Comment by adithyankv** [comment]
Or perhaps something like this.

![convert](https://user-images.githubusercontent.com/29067795/133949989-3cc15f75-8485-497c-af52-9853eda96c53.png)

![wheel-cutout](https://user-images.githubusercontent.com/29067795/133950405-c30b4b89-5f2b-46af-b5be-3319cf52b467.png)


this was heavily inspired by [Ronny Do ColorPicker icon](https://github.com/RonnyDo/ColorPicker/blob/master/data/icons/64/com.github.ronnydo.colorpicker.svg)

**Comment by ckruse** [comment]
I like the first two and both of the second suggestion. Its looking good!

**Comment by adithyankv** [comment]
Oh hey cool.
Then I'll may be pick one of each and pixel fit them to the different dimensions. Check how they look in the dock, app launcher etc. and then select one and submit a pull request.

**Comment by adithyankv** [comment]
Used this icon as this seems to be the one that works best at all sizes. Created a pull request with the new icons.

![colormate-icons-demo](https://user-images.githubusercontent.com/29067795/134074673-5398f5c0-47a4-4a0e-9bfa-b30ebbb95c2a.png)
